# Site settings
title: fuckTimer
description: Hello, that's the official fuckTimer page.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: fuckTimer
user_title: CS:GO RESTful API based SourceMod Timer
email: anon@anon.com
twitter_username: fuckTimer
github_username:  fuckTimer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
