# Site settings
title: fuckTimer
description: Hello, that's the official fuckTimer page.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: fuckTimer
user_title: RESTful API based SourceMod Timer for CS:GO

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
